### ISSUE TITLE
nosite and nousersite: shouldn't those be the default?

### ISSUE THREAD

**Issue by EdSchouten** [NuxiNL/cloudabi-ports#19]
Hi @moreati,

Maybe I'm simplifying things by a bit too much, but what's the reason why we have `nosite` and `nousersite` in our argdata parsing? Wouldn't it make more sense to turn `path` into a sequence instead of a file descriptor and use that to list all the standard paths?

The point is, without `nosite` set, Python even fails to start. Ideally Python should work with only a small number of flags set.

**Comment by moreati** [comment]
That code is whatever I could get working to reach Hello World. It doesn't represent good design.

I agree we should make `nosite: true, nousersite: true` the defaults (or possibly `site: false, usersite: False` to avoid the double negative). That's the opposite of Python on Unix, but it's more CloudABI-thonic.

I agree `path` should be a sequence. Again, what's there now is just what I could get working quickly.

**Comment by EdSchouten** [comment]
Gotcha! I already flipped this around in 3e90720d43a245fe4c9ecf9e19bf10d0e683ee0f. I should have mentioned this issue number in the commit message, of course.
