### ISSUE TITLE
Status of Python port

### ISSUE THREAD

**Issue by moreati** [NuxiNL/cloudabi-ports#2]
In the 32C3 talk it was mentioned that a port of Python to CloudABI is in progress. Is this WIP publicly available? Would you be interested in help finishing it?

**Comment by EdSchouten** [comment]
Hi Alex,

Yes! I would be very much interested in having other people help me complete the Python port. To be honest, getting Python to work is really high on my todo list, but I am by no means a Python expert. Having someone else look over my shoulder (or vice versa) would be very useful.

On my workstation at home I have a partial port of the Python interpreter to at least get most of it to compile. The only problem is that I can't provide you a copy of my patchset right now, as my workstation is literally on the other side of the world. I'm on a holiday until February 12th. ;-)

I'll update this bug when I manage to push my changes into a separate branch after I get back home!

**Comment by EdSchouten** [comment]
Hi Alex,

Sorry for letting you wait so long. I've just spent some time cleaning up the Python package and have pushed it in a separate branch, `python`. There is a fair chance I'll work towards completing it over the next month, but feel free to experiment with it as well.

Observe that I've added a `diff() + debug_shell()` block to the `BUILD` file. If you run `./build_packages.py python`, it'll spawn a shell right after configuring. Just run `make -k 2>&1 | grep ' error: ' | sort -u` and you'll get a list of all code that still needs patching up.

As long as you keep the shell open, you can edit the code and run `make` again. Once you leave the shell, a patch is automatically generated at the location used in the `BUILD` file.

**Comment by moreati** [comment]
I've forked this as https://github.com/moreati/cloudabi-ports/tree/python. It's still very much WIP, the build compiles, but segfaults running `Parser/pgen`. This also depends on the following uncommitted change

``` diff
--- a/src/distfile.py
+++ b/src/distfile.py
@@ -26,3 +26,3 @@ class Distfile:
         self._checksum = checksum
-        self._patches = patches
+        self._patches = sorted(patches)
         self._unsafe_string_sources = unsafe_string_sources
```

**Comment by moreati** [comment]
[My fork](https://github.com/moreati/cloudabi-ports/tree/python) is progressing and I've learned quite a bit about autoconf and C. It now successfully builds a native python executable, then uses that to get part way through a cross-build. The current failure point is

```
/usr/obj/cloudabi-ports/bin/x86_64-unknown-cloudabi-cc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -O2 -fsanitize=safe-stack -Werror=implicit-function-declaration -Werror=date-time -O2 -fsanitize=safe-stack -Werror=implicit-function-declaration -Werror=date-time  -Werror=declaration-after-statement   -I. -IInclude -I/usr/obj/cloudabi-ports/build/0/Python-3.5.1/Include    -DPy_BUILD_CORE  -c /usr/obj/cloudabi-ports/build/0/Python-3.5.1/Modules/zipimport.c -o Modules/zipimport.o
/usr/obj/cloudabi-ports/build/0/Python-3.5.1/Modules/zipimport.c:109:13: warning: code will never be executed [-Wunreachable-code]
        if (rv == -2)
            ^~
/usr/obj/cloudabi-ports/build/0/Python-3.5.1/Modules/zipimport.c:879:10: error: implicit declaration of function '_Py_fopen_obj' is invalid in C99
```

I'll keep at it.

**Comment by EdSchouten** [comment]
Pretty awesome! I think that specific code doesn't  want to build, because you disabled `_Py_stat()`. It may be worth to remove the `-Wunreachable-code` compiler flag in this specific case.

**Comment by EdSchouten** [comment]
Now that the Python package has landed, let's close this issue. Making the Python package more functional is something we'll have to continue working on indefinitely... ;-)
