### ISSUE TITLE
Bad C99 features test fails with UnicodeDecodeError in m4-1.4.17/configure

### ISSUE THREAD

**Issue by dckc** [NuxiNL/cloudabi-ports#22]
I can't seem to actually build any packages.

The _Bad C99 features test_ in `src/builder.py` (line 175) seems to expect ASCII:

``` python
                with open(path, 'r') as fin, open(path + '.new', 'w') as fout:
                    for l in fin.readlines():
                        # Bad C99 features test.
                        if l.startswith('#define showlist(...)'):
```

but there are non-ASCII characters (`nonascii.py` is given below):

```
root@8c58f1859b17:/cloudabi-ports# python3 nonascii.py /usr/obj/cloudabi-ports/build/0/m4-1.4.17/configure
25454:b'      const char input[] = "B\\217\\253\\344\\217\\251\\316er"; /* "B\xc3\xbc\xc3\x9fer" */\n'
 ==> [(63, 195), (64, 188), (65, 195), (66, 159)]
...
```

The result is:

```
root@8c58f1859b17:/cloudabi-ports# python3 -i ./build_packages.py expatINFO:src.package:BUILD m4
INFO:src.distfile:CHECKSUM /cloudabi-ports/_obj/distfiles/m4-1.4.17.tar.xz
Traceback (most recent call last):
  File "./build_packages.py", line 64, in <module>
    build_package(target_packages[(name, arch)])
...
  File "/cloudabi-ports/src/builder.py", line 76, in gnu_configure
    for l in fin.readlines():
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5709: ordinal not in range(128)
```

`nonascii.py` is:

``` python
import sys

for row, line in enumerate(open(sys.argv[1], 'rb').readlines()):
    non_ascii = [(col, b) for (col, b) in enumerate(line) if b > 127]
    if non_ascii:
        print('{row}:{line}\n ==> {other}'.format(
            row=row, line=line, other=non_ascii))
```
## Environment

I'm running on Ubuntu 16.04 in a docker container: [Dockerfile gist](https://gist.github.com/dckc/9159265bbf979fc4315e08cda2420d3a)

I used `docker build -t cloudabi-toolchain .` to build the docker image and then `docker run --rm -ti -v /usr/local/src/cloudabi-ports:/cloudabi-ports cloudabi-toolchain bash` to start the container. I have the current version of the code (e60305b9d11f12) checked out in `/usr/local/src/cloudabi-ports`.

**Comment by EdSchouten** [comment]
That's interesting. That issue must have been present since December 2015, as that's when I last updated the m4 package. I seem to recall that the BSDs are a bit more relaxed about what they consider valid text if the default locales are used.

I've just attempted to fix this by using binary strings here. Should be good enough. Thanks for reporting this!

(Also worth mentioning: there is no need to have a cross compiler for CloudABI installed when using cloudabi-ports; it already builds a copy during bootstrap. The reason for this is that it's the only way we can get reproducible builds.)

**Comment by dckc** [comment]
> there is no need to have a cross compiler for CloudABI installed when using cloudabi-ports; it already builds a copy during bootstrap.

Now you tell me ;-)

**Comment by dckc** [comment]
> I've just attempted to fix this by using binary strings here.

I fixed it by specifying the encoding in `open()`. I should have submitted a PR.

I tried `export LOCALE=C` without luck. I suspect that is the relevant difference in our environments, though.
