### ISSUE TITLE
Python's 'path' needs to be a list instead of a single path object

### ISSUE THREAD

**Issue by EdSchouten** [NuxiNL/cloudabi-ports#26]
Right now 'path' in the Python schema needs to be a single element. This is obviously flawed, as in practice you'd want to be able to set multiple include paths.

**Comment by EdSchouten** [comment]
Fixed! This commit changes the schema of the Python YAML file, so that `path` has to be a list of file descriptors. Before:

    path: !file
        path: /some/path

After:

    path:
        - !file
            path: /some/path1
        - !file
            path: /some/path2

I've fired up a new package build, which I expect to be finished in a couple of hours. I've also updated [the existing blog post](https://nuxi.nl/blog/2016/08/01/cloudabi-python.html) to use the new schema.

CC @dckc

**Comment by dckc** [comment]
Thanks for the fix; I'd really like to try it out, but...

I don't see the updated package. Is the new package build still running?

```
aarch64-unknown-cloudabi-python-3.6.0_32.txz       26-Dec-2016 15:19            24050712
```
 -- https://nuxi.nl/distfiles/cloudabi-ports/freebsd/

**Comment by EdSchouten** [comment]
Sorry for the delays. I encountered a regression during the package builds, meaning that I had to fix that first and restart. I've just pushed proper packages that include this. Enjoy!

**Comment by EdSchouten** [comment]
By the way, another thing that I added to the latest version of Python is `script` instead of `command`:

    script: !file
        path: whatever.py

In other words: no need to embed Python code in the YAML. You can just specify the file containing the entry point.
