### ISSUE TITLE
LLVM SafeStackColoring calculateLiveIntervals assertions

### ISSUE THREAD

**Issue by laanwj** [NuxiNL/cloudabi-ports#28]
Not sure where to file this, but I'm experimenting with porting a moderately complex C++ package to cloudabi (Bitcoin Core).

In two files I've got the following crash while compiling:
```
Assertion failed: (!Started.test(AllocaNo)), function calculateLiveIntervals, file /wrkdirs/usr/ports/devel/llvm39/work/llvm-3.9.1.src/lib/CodeGen/SafeStackColoring.cpp, line 217.
```
It looks like: https://bugs.llvm.org//show_bug.cgi?id=30318

Versions:
```
Platform: FreeBSD 11.0-RELEASE-p2
cloudabi-toolchain-1.7         C and C++ toolchain for CloudABI
cloudabi-utils-0.18_1          Utilities for running CloudABI programs
```

Attached debug files:
```
PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-3.9: note: diagnostic msg: /tmp/server-ed8244.cpp
clang-3.9: note: diagnostic msg: /tmp/server-ed8244.sh
clang-3.9: note: diagnostic msg: 
```
Associated debug files: [server-ed8244.tar.gz](https://github.com/NuxiNL/cloudabi-ports/files/802169/server-ed8244.tar.gz)

**Comment by EdSchouten** [comment]
Hi Wladimir,

Nice! That sounds like a very interesting project. Good news: literally 10-15 minutes ago I changed the `devel/cloudabi-toolchain` port to use `devel/llvm40` as its compiler. According to the bug report, this got fixed in September last year, so the fix should be part of LLVM 4.0.

Could you upgrade to `cloudabi-toolchain-1.8` and let me know whether that fixes things? Thanks!

Edit: Also worth mentioning: `make -C /usr/ports/devel/cloudabi-toolchain LLVM_SUFFIX=... install clean` is a quick and dirty way to install a CloudABI toolchain using an arbitrary LLVM version. For example, passing in `LLVM_SUFFIX=-devel` will make it use `devel/llvm-devel`.

**Comment by laanwj** [comment]
Thanks, I'll try that.

Yes it seems an interesting project to port. Also somewhat challenging as a lot of use is made of files (from two different databases!) and the global namespace. The biggest stumbling block is the use of `boost::filesystem`. The plan is to move away from that (well, from Boost in general) in the longer run. But it would be awesome if `boost::filesystem` could be made to work with FD-relative paths. I'll probably end up with some kind of boost::filesystem-ish wrapper, as we use only a small subset of its functionality.

Another challenge is the networking code. As a P2P daemon it's kind of expected to be able to make outgoing connections. A quick workaround I see for this is to pass in a fd that can make connections to a SOCKS proxy (such as Tor), which acts as the "guard".

**Comment by EdSchouten** [comment]
Yes, the entire filesystem thing is a bit messy. It's also a shame that the C++ working group slightly messed up with this by simply standardising `boost::filesystem` with little to no changes, even though multiple parties expressed their concerns that it is not injectable, testable, etc.

What's very good news is that some folks are working on fixing this, but my fear is that this won't make it into the final version of C++17, meaning we'll be stuck with this problem for quite some time to come.

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0544r0.html

**Comment by laanwj** [comment]
> Could you upgrade to cloudabi-toolchain-1.8 and let me know whether that fixes things? Thanks!

Do I need to do something special for that? `pkg update` `pkg upgrade` is not giving me it.

**Comment by EdSchouten** [comment]
The binary packages at FreeBSD always lag a couple of days behind what's in the Ports repository, as the builders still need to be kicked off to upload new binary packages.

The quick and dirty way of getting this to work without using the Ports tree is to run `pkg install llvm40` and then alter the existing symlinks created by the `cloudabi-toolchain` port as follows:

```
lrwxr-xr-x  1 root  wheel  21 Feb 26 20:09 /usr/local/bin/x86_64-unknown-cloudabi-c++ -> ../llvm40/bin/clang++
lrwxr-xr-x  1 root  wheel  19 Feb 26 20:09 /usr/local/bin/x86_64-unknown-cloudabi-cc -> ../llvm40/bin/clang
lrwxr-xr-x  1 root  wheel  26 Feb 26 20:09 /usr/local/llvm40/x86_64-unknown-cloudabi -> ../x86_64-unknown-cloudabi
```

**Comment by laanwj** [comment]
Thanks, that seemed to have solved it!

**Comment by EdSchouten** [comment]
Nice! Then I think we'd better mark this specific issue as closed.

Feel free to open up any other issues (both in this repo or any of the others if it's more applicable) in case you stumble upon any other problems or have questions in general!
