### ISSUE TITLE
RFC: Mailing list(s)/forum(s) for cloudabi discussion?

### ISSUE THREAD

**Issue by moreati** [NuxiNL/cloudabi-ports#8]
Given questions/answers currently on Twitter it would be nice to have a less terse, more dedicated venue to direct people to.

Do you have a preference for
- The format (e.g. a mailing list, a web forum, google groups, github issues ...)?
- A particular domain (e.g. nuxi.nl, freebsd.org, cloudabi.tld ...)?

Assuming you're happy with the concept, would you like me to set something up?

**Comment by EdSchouten** [comment]
Hi there,

I already created a mailing list on Google Groups some time ago: https://groups.google.com/forum/#!forum/cloudabi-devel.

Unfortunately, I didn't do a really good job at announcing its existence; it was only mentioned in the cloudlibc readme. I've just extended the cloudabi-ports readme, but will also list it from the nuxi.nl website.

If you can think of some other places where I can improve docs, etc. just let me know. Thanks!
